# Generated by Django 5.1.5 on 2025-02-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0008_jobseeker_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker_resume',
            name='user',
        ),
    ]
