# Generated by Django 5.1.5 on 2025-03-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0044_delete_companynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
