# Generated by Django 5.1.5 on 2025-03-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0045_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=1255, null=True),
        ),
    ]
